apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quickstart-to-qmgr-traffic
spec:
  host: to2e-qmgr.chl.mq.ibm.com
  to:
    kind: Service
    name: mq-tls-ini-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
