apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: base-image
  namespace: mq
spec:
  # params:
  #   - description: "image-registry.openshift-image-registry.svc:5000/mq/pipeline-mq:v1"
  #     name: IMAGE_NAME
  #     type: string
  tasks:
    - name: git-clone
      params:
        - name: GIT_SECRET
          value: "git-credentials"
        - name: GIT_SCRIPT
          value: "git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/IBMMQAutomation/base-image.git"
        - name: SCAN_SECRET
          value: image-scan-credentials
        - name: subdirectory
          value: "base-image"
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/mq/pipeline-mq:v1"
        - name: TLSVERIFY
          value: "false"
        - name: PROJECT
          value: mq
        # - name: QM_YAML
        #   value: mq-queue-manager.yaml
        - name: OCP_SECRET
          value: "ocp-credentials"
      taskRef:
        kind: Task
        name: base-image-task
